### ISSUE TITLE
Add information to old survxai repo

### ISSUE THREAD

**Issue by mikolajsp** [ModelOriented/survex#1]
Add information to [https://github.com/mi2dataLab/survxai](https://github.com/mi2dataLab/survxai) readme that the package won't be maintained.

**Comment by hbaniecki** [comment]
Let's do this after the CRAN release

**Comment by hbaniecki** [comment]
https://github.com/MI2DataLab/survxai/commit/ee5c7df52b347e422efcf028bf2afe652284fb2d
