### ISSUE TITLE
Allow the user to remove the subtitle in plots

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/survex#11]
At this moment, plot functions with the `subtitle` parameter have it set to `NULL` as default.

Therefore, it is not possible for the user to remove the subtitle using the conventional `subtitle=NULL` value.

Perhaps set a different default value? It is clearly not `NULL`, because the subtitle appears by deafult.

https://github.com/ModelOriented/survex/blob/561b62ece953ca5adae6280dce6ead4bf0588bf9/R/plot_surv_feature_importance.R#L73-L76

**Comment by mikolajsp** [comment]
You can set it to `""` for no subtitle but I agree `NULL` as default parameter isn't the best option.

**Comment by hbaniecki** [comment]
`""` creates a margin between the title and plot.
