### ISSUE TITLE
Add `plot.model_profile` for two or more models 

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/survex#12]
`plot.model_profile` in DALEX/ingredients uses the `color` parameter to choose a dimension for plot splitting, e.g. by the model (label). This allows for comparing two models in one plot.

```r
library(DALEX)

titanic_glm_model <- glm(survived~., data = titanic_imputed, family = "binomial")
explainer_glm <- explain(titanic_glm_model, data = titanic_imputed, verbose = FALSE)
expl_glm <- model_profile(explainer_glm)

library("ranger")
titanic_ranger_model <- ranger(survived~., data = titanic_imputed, num.trees = 50,
                               probability = TRUE)
explainer_ranger  <- explain(titanic_ranger_model, data = titanic_imputed, verbose = FALSE)
expl_ranger <- model_profile(explainer_ranger)

plot(expl_ranger$agr_profiles, expl_glm$agr_profiles, color = "_label_") 
plot(expl_ranger$agr_profiles, expl_glm$agr_profiles)
```

It would be nice to have similar functionality in `survex`
```r
ve_rf <- model_profile(explainer_rf, variables = "age")
plot(ve_rf)
ve_cox <- model_profile(explainer_cox, variables = "age")
plot(ve_cox, ve_rf) # won't work
```

**Firstly, at this moment the above code should return an error** 

The idea is to add some `facet` parameter, which by default is set to `variables` but can be changed to `_label_` etc.

```r
plot(ve_cox, ve_rf, facet="_label_")
```

Mockup:

![image](https://user-images.githubusercontent.com/32574004/197189594-f2f50178-acdd-45d0-a3fc-24e738878acd.png)

Using:
```r
(plot(ve_rf) + ggtitle("rsf")) +
  (plot(ve_cox) + ggtitle("cph")) + 
  plot_annotation(subtitle="")
```

**Comment by mikolajsp** [comment]
I agree this is useful functionality. I'm just wondering how to show this information in one plot.

Do you think one column per model would be a good way to show it? and then different  variables in rows?

**Comment by hbaniecki** [comment]
Perhaps, the most popular use cases consider 1-2-4 variables and 1-2-3 models.
