### ISSUE TITLE
`facet_ncol` is missing in `plot_individual_ceteris_paribus_survival`

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/survex#13]
See
https://github.com/ModelOriented/survex/blob/561b62ece953ca5adae6280dce6ead4bf0588bf9/R/plot_surv_ceteris_paribus.R#L172
and
https://github.com/ModelOriented/survex/blob/561b62ece953ca5adae6280dce6ead4bf0588bf9/R/plot_surv_ceteris_paribus.R#L189

Also, should `scales` be used here?
https://github.com/ModelOriented/survex/blob/561b62ece953ca5adae6280dce6ead4bf0588bf9/R/plot_surv_ceteris_paribus.R#L215

**Comment by mikolajsp** [comment]
Actually, I've removed the `facet_ncol` and `title` arguments from the `plot_individual_ceteris_paribus_survival()` function, as they are not needed. It always draws one subplot for one variable, and the faceting is only to get the name of the variable printed over the plot in the same way as the others. Faceting is done by another function.
