### ISSUE TITLE
different legend titles in `plot.model_profile` between `categorical` and `numerical` plots

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/survex#14]
For some reason, when plotting `model_profile` for categorical variables, the legend title disappears
https://github.com/ModelOriented/survex/blob/561b62ece953ca5adae6280dce6ead4bf0588bf9/R/plot_surv_ceteris_paribus.R#L213
but for numerical variables, it is set to the variable's name
https://github.com/ModelOriented/survex/blob/561b62ece953ca5adae6280dce6ead4bf0588bf9/R/plot_surv_ceteris_paribus.R#L161-L162

Does copying code from numerical (2) to categorical (1) break something?

**Comment by mikolajsp** [comment]
fixed in #15
