### ISSUE TITLE
Once per few checks, macOS-latest fails

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/survex#4]
No idea why

![image](https://user-images.githubusercontent.com/32574004/189537947-3ff3e640-2318-41ee-a0e0-8f0c3673016e.png)

> Error: Error: processing vignette 'survex-usage.Rmd' failed with diagnostics: polygon edge not found

**Comment by mikolajsp** [comment]
I've also seen this, have no idea why.

![image](https://user-images.githubusercontent.com/55801784/189538920-d72abf27-b772-431c-a366-424ddeec5e9e.png)

I think it's the first problem [here](https://github.com/r-lib/actions#common-questions). I will try to fix this

**Comment by mikolajsp** [comment]
Seems it was fixed in https://github.com/ModelOriented/survex/commit/fe60e398d0518a0a37f9f6ccd9197bffb458adcd

If this happens again reopen this, I will debug further.

**Comment by hbaniecki** [comment]
maybe it will fix itself in the near future..

**Comment by mikolajsp** [comment]
The issue seems to have been missing Arial font on macos. I added a step to install it in the check environment. But let's wait with closing this until a few commits pass.
