### ISSUE TITLE
question about C/D AUC from model_performance()

### ISSUE THREAD

**Issue by mao223** [ModelOriented/survex#5]
Good day, I could not find information about what specific C/D AUC measure was used in the manual (see https://doi.org/10.1186/s12874-017-0332-6). Could you please provide a reference? Thank you for this amazing package.

**Comment by mikolajsp** [comment]
Hello,

Thank you for your interest in our package.

We use (CD5) from the article you mentioned, that is the estimator proposed by [Uno et al.](https://www.jstor.org/stable/27639883#metadata_info_tab_contents) and [Hung and Chang](https://www.jstor.org/stable/41000414#metadata_info_tab_contents).

We're planning to add references to our documentation so I'm not closing the issue for now.
