### ISSUE TITLE
How to understand the model_parts() to get the importantce of features

### ISSUE THREAD

**Issue by Phoenix12580** [ModelOriented/survex#69]
![image](https://user-images.githubusercontent.com/55424563/226389246-8f02f946-7b99-469d-9d56-199861c021ad.png)

I could not understand the result and choose the important features. 

When I search permutation, they showed permutation result is this  
![image](https://user-images.githubusercontent.com/55424563/226391469-c2cdabb2-e022-422d-9f1a-0e5a4612e67b.png)

I look forward to your explanation of the results, and I greatly appreciate the tool you provided.

**Comment by krzyzinskim** [comment]
`model_parts()` function measures importance of features in terms of model’s performance change if the effect of a selected explanatory feature is removed (which is simulated by permuting feature values). The greater the drop in performance, the more important the feature.

Thus, the meaning of the columns in the resulting data frame is as follows:
- `_times_` - time point for which we calculate importance in a corresponding row of data frame (features can have different importances over time in survival models), 
- `_full_model_` - the loss of full model without permuting any variable (0 if `type` is set to `"difference"` which is default) - so you are right, it refers to the complete model trained using all features, 
- `_baseline_` - the loss of full model with permuted response vector `y`,
- `permutation` - just the number of a permutation round to which the results refer in a given row (permutations are repeated for a more stable result and then averaged - averaged values are saved in rows with `permutation=0`). 
Then, in each column with a variable name, there are importance values of that feature at different time points. 

Hence, the graph you send shows the average importance of the variables over time (corresponding to all rows with permutation = 0). On the Y-axis is the loss in performance of the model after permutation (removal of the effect) of the variable in question - the greater/higher, the more important the variable. So I agree that `karno` in the example given is the most important variable. However, it can be seen that over time the `celltype` variable is just as important or even more important. 

If you want to aggregate the importance to a single number for every variable you can integrate the resulting curves/functions. It can be done by changing `loss_function` parameter, for example:

```R
cph_model_parts_integrated <- model_parts(cph_exp, loss_function = integrated_brier_score)
plot(cph_model_parts_integrated)   
``` 
It produces barplot with aggregated importance values. 
![image](https://user-images.githubusercontent.com/56126737/227500537-fa5d18ee-437f-484a-a7e0-46bbc40937ed.png)

Hope this clears up your doubts and concerns. If you have any further ones, feel free to ask 🙂
