### ISSUE TITLE
Parallel analysis for model_parts function

### ISSUE THREAD

**Issue by MosquitoFan** [ModelOriented/survex#71]
Is there any parallel analysis in the model_parts function? I want to compute the importance of 5K features. The R only uses 10% CPU and 15% memory, I want to make full use of the CPU to save time.

Thank you so much.

BTW, for the m_parts, there are permutations from 0 to 10, which 

> _permutation_

used in the plot(m_parts)?  I am now thinking the plot use 

> _permutation_ = 0

**Comment by krzyzinskim** [comment]
Unfortunately, it is not currently possible to parallelize calculations of `model_parts()` 🙁 But we will add this as a long-term goal. 

For now, as calculations can take a long time, it may be worth using the progress bar. You can do this as follows:
```R
progressr::with_progress(model_parts(rsf_exp, loss_function=loss_one_minus_cd_auc, type="difference"))
```

Only permutations 1, ..., B (`B=10` by default) are valid permutations. The rows of resulting data frame with `permutation=0` are the aggregated (averaged) variable importances from these B permutations. This is why the `plot(m_parts)` displays these values.

**Comment by MosquitoFan** [comment]
> 

Thank you so much, it took about 3 days to compute the importance for 1400 patients with 5000 features, hope the parallel function coming soon!
