### ISSUE TITLE
Feature: add support for computing SurvSHAP using treeshap-algorithm

### ISSUE THREAD

**Issue by kapsner** [ModelOriented/survex#75]
The purpose of this formal feature request is mainly for a documentation of ongoing works and to avoid duplicate efforts.

I've started to work on implementing support for computing SurvSHAP values using the `treeshap` algorithm in [this fork](https://github.com/kapsner/survex/tree/feat-treeshap) of `survex`.

As of now, both, local and global computation of SurvSHAP values using the `ranger` algorithm work technically.

Statistical / mathematical correctness needs yet to be proven for:
- [x] computation of predictions of the survival probability at different time points using treeshap
  + see [this issue](https://github.com/ModelOriented/treeshap/issues/24)
  + related code is located [here](https://github.com/kapsner/treeshap/blob/master/R/unify_ranger_surv.R#L88)
  + one possibly required enhancement includes to use the stepfunction logic [from here](https://github.com/ModelOriented/survex/blob/main/R/utils.R#L106) in the treeshap-package to apply it to the predictions from ranger in order to address that currently, only the time-points that are computed internally by ranger are used for computing the survival probabilities (see [here](https://github.com/kapsner/treeshap/blob/master/R/unify_ranger_surv.R#L92)), which results in [this code in survex](https://github.com/kapsner/survex/blob/feat-treeshap/R/surv_shap.R#L94) and which is some kind of a workaround currently
- [x] calculation of aggregated "global" survshap values for each time-point and feature across multiple observations
  + see [this PR](https://github.com/ModelOriented/survex/pull/74)

**Comment by kapsner** [comment]
Regarding the computation of the prediction of the survival probability at predefined time points using treeshap, the latest code adaptions seem to work well: the SurvSHAP-plot computed with treeshap produces very similar results compared to the one computed with kernelshap (but computation with treeshap was faster).

Plot with Treeshap (code-ref https://github.com/kapsner/survex/blob/d2c16a608792c6387b2e65890446521890d088e0/tests/testthat/test-predict_parts.R#L122):
![surv_treeshap](https://user-images.githubusercontent.com/44973495/230729121-65b93b65-cb8b-4165-97e2-d951e517b27d.png)


Plot with Kernelshap (code-ref https://github.com/kapsner/survex/blob/d2c16a608792c6387b2e65890446521890d088e0/tests/testthat/test-predict_parts.R#L137):
![surv_kernelshap](https://user-images.githubusercontent.com/44973495/230729104-e36412ff-3255-4226-87fa-d3a513f71995.png)

**Comment by mikolajsp** [comment]
Completed in #87
