### ISSUE TITLE
Suggestion on progressr

### ISSUE THREAD

**Issue by HenrikBengtsson** [ModelOriented/survex#83]
Hello,

while troubleshooting a false-positive CRAN NOTE, I noticed that you use:

```r
if (requireNamespace("progressr", quietly = TRUE)) prog()
```

in several places.  You can avoid the quite expensive(*) calls to `requireNamespace("progressr", quietly = TRUE)` if you do:

```r
if (requireNamespace("progressr", quietly = TRUE)) {
  prog <- progressr::progressor(along = 1:((length(variables) + 2) * B))
} else {
  prog <- function() NULL
}
```

Then you can replace:

```r
if (requireNamespace("progressr", quietly = TRUE)) prog()
```

with

```r
prog()
```

(*) `requireNamespace()` hits the file system each time if **progressr** is not installed.

**Comment by mikolajsp** [comment]
Hi,

thanks for the suggestion, this is a very easy fix and we're just working on a new release, I'll try to do it today.

**Comment by mikolajsp** [comment]
Hopefully this is resolved in 96b3f3f7c09dcbfbcf89c5f45b97f3ea151abfac.

**Comment by HenrikBengtsson** [comment]
LGTM. FYI, `progressor()` has `steps` argument, so you don't have to create an auxillary `along` argument.  That is, you can use

```r
prog <- progressr::progressor(steps = (length(variables) + 2) * B)
```

instead.

**Comment by mikolajsp** [comment]
Thanks! I'll change that as well.
