### ISSUE TITLE
Integration method for time-dependent measures

### ISSUE THREAD

**Issue by mikolajsp** [ModelOriented/survex#9]
At this time, for calculation of Integrated Brier Score and Integrated AUC is performed as Riemann integral. This leads to a great influence of times at the end of the considered time-frame (where there might be few observations) on the integrated score.

Two proposed normalization methods are in [1]. We should try to implement (one of/both of) these methods.

There should also be a possibility to cut off the integration at different quantiles of times in the data (Q25, Q50, Q75) [2]

- [[1] E. Graf, C. Schmoor, W. Sauerbrei, and M. Schumacher, “Assessment and comparison of prognostic classification schemes for survival data,” Statistics in Medicine, vol. 18, no. 17-18, pp. 2529–2545, 1999.](https://doi.org/10.1002/(sici)1097-0258(19990915/30)18:17/18%3C2529::aid-sim274%3E3.0.co;2-5) 
- [[2] P. Kopper, S. Wiegrebe, B. Bischl, A. Bender, D. Rügamer, “DeepPAMM: Deep Piecewise Exponential Additive Mixed Models for Complex Hazard Structures in Survival Analysis”. Advances in Knowledge Discovery and Data Mining. PAKDD 2022.](https://doi.org/10.1007/978-3-031-05936-0_20)

**Comment by hbaniecki** [comment]
Also, later use it to update the choice of `max_vars` in feature importance.

https://github.com/ModelOriented/survex/blob/561b62ece953ca5adae6280dce6ead4bf0588bf9/R/plot_surv_feature_importance.R#L55
