### ISSUE TITLE
 Partial Dependence plots exclusively for a specific set of observations

### ISSUE THREAD

**Issue by dmresearch15** [ModelOriented/survex#90]
I'm utilising the model_profile function for Partial Dependence analysis. Is it feasible to generate Partial Dependence plots exclusively for a specific set of observations? Additionally, I'm seeking a similar capability with the model_profile_2d function.

**Comment by krzyzinskim** [comment]
Unfortunately, this is not possible. `model_profile` and `model_profile_2d` calculate profiles for the set of observations contained in `explainer$data`, which is the same behavior as in the `DALEX` package.
