### ISSUE TITLE
error in evaluating the argument 'x' in selecting a method for function 't': attempt to set 'colnames' on an object with less than two dimensions

### ISSUE THREAD

**Issue by lzxcvn** [ModelOriented/survex#91]
I encountered the following error while explaining the mboost learner for the MLR3 package. What is the reason for this?
![image](https://github.com/ModelOriented/survex/assets/104612436/21aeb1aa-0f99-42fd-b644-9982f11224d4)
![image](https://github.com/ModelOriented/survex/assets/104612436/1cb046f8-7f9f-468d-8234-1106434ae0de)
![image](https://github.com/ModelOriented/survex/assets/104612436/92746acf-e891-4e6b-a0a0-256e62408cd9)
![image](https://github.com/ModelOriented/survex/assets/104612436/69923ce6-d2b3-4f48-be3c-c3c479a80054)
![image](https://github.com/ModelOriented/survex/assets/104612436/46bd71ce-0dd1-4add-88c4-03c99bf8d775)
![image](https://github.com/ModelOriented/survex/assets/104612436/3a445a25-1525-4b93-9c9e-6bfb6cbd7b77)
![image](https://github.com/ModelOriented/survex/assets/104612436/be544318-84cf-41e9-af3a-df900bf7beee)

**Comment by krzyzinskim** [comment]
I've tried to reproduce the error and found that it is rather not related to `survex` package itself. It stems from `mlr3proba` and `mboost` used underneath. Not sure how your `surv_pred` function look like but I see it uses the `$predict_newdata` method (line 16.), which gives this error when predicting for one observation represented as one row of `data.frame`, even outside the `survex`. 

The solution would be to use another model from `mlr3proba` and report this error.

**Comment by lzxcvn** [comment]
> `survex`我尝试重现该错误，发现它与包本身无关。它源自`mlr3proba`并`mboost`在下面使用。不确定你的`surv_pred`函数是什么样的，但我看到它使用了`$predict_newdata`方法（第 16 行），该方法在预测表示为一行的一个观察值时给出此错误`data.frame`，即使在`survex`.
> 
> 解决方案是使用另一个模型`mlr3proba`并报告此错误。

Thank you for your reply. After switching to another function, this issue was resolved. It seems that each learner has its own applicable function.
